services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app             # Monta el directorio de la aplicación
      - ./database.db:/app/database.db  # Asegura que la base de datos esté disponible en el contenedor
    environment:
      - FLASK_ENV=development
